### PR TITLE
Added an interface for the CompleteTaskPresenter 

### LINKED ISSUE #102: [Subissue 4.6] Adding Interface for the UI

### PR DESCRIPTION
**Pull request by bmguiler**
The CompleteTaskPresenter now holds a reference to a list of CompleteTaskUiInterfaces that can be implemented by the UI. The class that implements this interface will need to implement a method called updateView, which the presenter uses to return a message to the UI that the task was completed successfully.

I also fixed some method calls in @Eggathin 's classes where the CompleteTaskPresenter was called without parameters, so I added the new parameter to those calls.

### CODE REVIEW

**Review by Eggathin — APPROVED** [review]
Interface will be helpful in calling the correct task to display on the UI, edits to the UI code itself is also welcome

**Review by dadler83 — APPROVED** [review]
Looks good, smart move with the observer pattern!

**Review by Amir1441 — APPROVED** [review]
The observer pattern interface was a great move by @MMachado05. It allows a lot to be done. Great work

**Review by Bhan-Aayush — APPROVED** [review]
This looks good. The CompleteTaskPresenter should solve any disputes we had earlier.

**Comment by MMachadoUofT** [comment]
This looks excellent! Since I know you're busy and you have all the approvals you need, I'll go ahead and update the branch so it can be merged.

**Pull request merged**
