### PR TITLE
107 final refactoring features and testing before submission

### LINKED ISSUE #107: Final refactoring, features, and testing before submission
- [] Connect Create Task window
- [] Bug catching for invalid inputs
- [] Update and try to run testing modules
- [] Update documentation

### PR DESCRIPTION
**Pull request by dadler83**
This PR is for the final refactoring and features of the project, mostly for code cleaning and testing additions. Additional doc strings will be added in another PR.
New Features:
- Create Task UI connected and functional
- New testing modules for missing use case tests -- 3 new testing suites

Bugfixes:
- IDs have been bug-fixed
- All windows have been linked together
- Inputting unexpected inputs no longer causes program crashes; just an error message sent to the user

Other:
- Refactoring / Repackaging

Testing: running the entire testing module, and experimenting with the running the program with the Main driver.

Note: A collaborative effort PR including communal changes over Zooms, requires everyone's approval!

### CODE REVIEW

**Review by Amir1441 — DISMISSED** [review]
Final refactoring done and any small changes made, looks good and ready for presentation

**Comment by MMachadoUofT** [comment]
I'll work on this branch to make any necessary documentation changes, as well as to assure we aren't getting any easily-fixable IntelliJ errors. Once I've complete my piece of the final work, I'll approve the PR so we can have our completed and refactored project

**Review by MMachadoUofT — APPROVED** [review]
Phew, this was a big one! I'm so happy that all of the pieces of code we've written these last 5 weeks have come together so effectively. All unit tests pass, the code is fully functional within the bounds of implemented features, it's well-packaged and thoroughly documented... this is definitely the hallmark of the work we've put into this! From here, all that's left is to merge this branch into main, and our program will be entirely finalized!

**Review by Bhan-Aayush — APPROVED** [review]
That's a lot of code being refactored, seriously great job guys. I think everything is good in terms of design patterns, clean architecture and refactoring from my side.

**Review by Eggathin — APPROVED** [review]
In short, the entire program has been refactored and allows for full functionality. Incredible work

**Review by bmguiler — APPROVED** [review]
Amazing! Look what we accomplished guys! Great work, and thanks to you guys for all the tidying up and refactoring. This is great :)

**Review by Amir1441 — APPROVED** [review]
The final boss we face of refactoring is done! Good work all

**Review by od-obas1187 — APPROVED** [review]
Everything looks great! With this refactoring done, now it's essentially just the presentation! Great job from the whole team :)

**Pull request merged**
