### PR TITLE
101 task tree UI tests 1

### LINKED ISSUE #101: Task Tree UI tests
Tests for the TaskTree use cases.

### PR DESCRIPTION
**Pull request by Bhan-Aayush**
Tests for the tasktreeUI, there are some bugs in it(which are commented out), but this is the basic idea of testing the tasktree UI. Please let me know if there is anything I can do.

### CODE REVIEW

**Comment by bmguiler** [comment]
you dont need to test each class of the use case, have one method with @Before that sets everything up, like creating a new task tree model, setting the interactor, controller and presenter to new instances of your classes, then have another method for testing it where you will call controller.getSubtrees() (which, if set up properly will go all the way through to your presenter) and then you test to make sure your presenter has the correct output by setting expectedPresenter = your expected output and actualPresenter = presenter.method (whatever your method is) and assert that expectedPresenter and actualPresenter are equals. Then you can also use Marcial's methods in the entities layer to test other details.

**Comment by MMachadoUofT** [comment]
It looks like the autograder isn't going to let this PR go through: I think the setWindowId vs setCurriculumId bug we were finding yesterday at Robarts is still intact. We might have to work to get that fixed if it hasn't been properly updated from main.

**Comment by Bhan-Aayush** [comment]
@MMachadoUofT That is what I feel is happening here. Good catch.

**Review by Eggathin — APPROVED** [review]
Good work on getting the tests written so soon, it will ensure that the task tree UI and its dependent classes function as intended

**Pull request closed without merging**
