### PR TITLE
Create new user registration use case

### LINKED ISSUE #39: [SubIssue 2.3] Create New User Registration Use Case

### PR DESCRIPTION
**Pull request by dadler83**
New features:
- folders refactored to follow standard naming conventions
- use case connected to LoginUI test branch
- Some necessary fields for testing implemented -- user factory and common user getter methods
- User storage system created (only has saving functionality as of now)
- tests for use case and UserStorage system written

Future:
Will add a cipher for user storage system so that saved data is encrypted and can be decrypted with password.
Will add edge case handling in UserStorage class for invalid files saved in wrong places

### CODE REVIEW

**Review by Amir1441 — APPROVED** [review]
Looks good to me! You always want to follow standard naming conventions in this manner. Also good to have tests for each use case which allow anyone to easily follow through the code.

**Review by MMachadoUofT — APPROVED** [review]
Wow, this is dense! The refactoring definitely looks good; we wanna make sure we have consistent naming conventions throughout. Your tests look good, as well, and it seems like this PR does a good job of following Clean Architecture and SOLID principles. Your Javadocs are also very good; the methods you've implemented are very easy to follow. It's unfortunate there were so many files to look at because of the package refactoring, though...

All in all, this is a solid PR. It'll definitely make connecting the GUI components easier in the future. Well done!

**Comment by od-obas1187** [comment]
This is a lot, but it all looks good! Everything seems to follow the Clean Architecture principles & SOLID, and the logic for the code itself seems to follow consistently, so I'm pretty certain functionality is a go, too.
No suggestions from me!

**Review by od-obas1187 — APPROVED** [review]
This is a lot, but it all looks good! Everything seems to follow the Clean Architecture principles & SOLID, and the logic for the code itself seems to follow consistently, so I'm pretty certain functionality is a go, too.
No suggestions from me!

**Pull request merged**
