### PR TITLE
Remaining backend entities

### LINKED ISSUE #1: [Feature 1] Create backend entities
Create the entity objects to be used in most use cases

- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14
- [x] #27

### PR DESCRIPTION
**Pull request by MMachadoUofT**
Due to time constraints, I've decided to bundle all remaining entities into a single PR linked directly with my feature issue. These involve implementing:

- [x] CommonTimeBlockManager
- [x] CommonCurriculum
- [x] CommonSchedule
- [x] CommonUser

The first is the most technically challenging, as adding new TimeBlocks according to the specification for what TimeBlockManager can do is a bit difficult. The last three, however, are functionally container class. The final to-do, CommonUser, is as simple as adding a single attribute. I intend on completing these by Friday night (November 25), or possibly by Saturday morning (November 26) the latest.

### CODE REVIEW

**Comment by MMachadoUofT** [comment]
This about completes my code for TimeBlockManager. The remaining code will tie it all together and hopefully result in a fully functional and tested backend. Exciting!

**Comment by MMachadoUofT** [comment]
This completes the Curriculum classes. All that's left are the Schedule class and adding a Schedule reference to the CommonUser class.

**Comment by MMachadoUofT** [comment]
Onto the final step; implementing the user. After this is done, the backend for our program should be fully functional.

**Review by bmguiler — DISMISSED** [review]
Thanks for hammering these out, now everyone should be able to complete their use cases and tests

**Review by bmguiler — DISMISSED** [review]

**Review by Bhan-Aayush — DISMISSED** [review]

**Review by Bhan-Aayush — APPROVED** [review]

**Review by bmguiler — APPROVED** [review]

**Review by Amir1441 — APPROVED** [review]

**Review by od-obas1187 — APPROVED** [review]
Great stuff! I'll be able to make tests with this now!👏

**Pull request merged**
